#[path = "codegen/generator.rs"]
mod generator;
#[path = "codegen/lexer.rs"]
mod lexer;
#[path = "codegen/parser.rs"]
mod parser;

use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use generator::generate_message_binding;
use lexer::Lexer;
use parser::Parser;

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let spec_path = manifest_dir.join("src").join("test.bcp");
    let generated_dir = manifest_dir.join("src").join("generated");

    println!("cargo:rerun-if-changed={}", spec_path.display());
    println!("cargo:rerun-if-changed=codegen/generator.rs");
    println!("cargo:rerun-if-changed=codegen/lexer.rs");
    println!("cargo:rerun-if-changed=codegen/parser.rs");

    let bcp_file = parse_bcp_file(&spec_path)?;
    fs::create_dir_all(&generated_dir)?;
    clear_generated_rust_files(&generated_dir)?;

    let mut module_contents =
        String::from("// @generated by build.rs\n#![allow(dead_code, unused_imports)]\n\n");

    for msg in &bcp_file.messages {
        let binding = generate_message_binding(msg)?;
        let binding_path = generated_dir.join(&binding.file);
        let module_name = module_name(&binding.file)?;

        fs::write(&binding_path, binding.contents)?;
        module_contents.push_str(&format!("mod {module_name};\n"));
        module_contents.push_str(&format!("pub use {module_name}::*;\n"));
    }

    fs::write(generated_dir.join("mod.rs"), module_contents)?;

    Ok(())
}

fn parse_bcp_file(path: &Path) -> io::Result<parser::BCPFile> {
    let contents = fs::read_to_string(path)?;
    let tokens = Lexer::new(&contents).decode().map_err(invalid_data)?;

    Parser::new(tokens).parse_tokens().map_err(invalid_data)
}

fn invalid_data(error: String) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error)
}

fn clear_generated_rust_files(dir: &Path) -> io::Result<()> {
    for entry in fs::read_dir(dir)? {
        let path = entry?.path();
        if path.is_file() && path.extension().and_then(|ext| ext.to_str()) == Some("rs") {
            fs::remove_file(path)?;
        }
    }

    Ok(())
}

fn module_name(path: &Path) -> io::Result<&str> {
    path.file_stem()
        .and_then(|stem| stem.to_str())
        .ok_or_else(|| {
            invalid_data(format!(
                "generated path `{}` has no module name",
                path.display()
            ))
        })
}
