#[path = "codegen/generator.rs"]
mod generator;
#[path = "codegen/lexer.rs"]
mod lexer;
#[path = "codegen/parser.rs"]
mod parser;

use std::env;
use std::fs;
use std::io;
use std::path::{Path, PathBuf};

use generator::generate_message_binding;
use lexer::Lexer;
use parser::Parser;

fn main() -> io::Result<()> {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let spec_path = manifest_dir.join("src").join("test.bcp");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    println!("cargo:rerun-if-changed={}", spec_path.display());
    println!("cargo:rerun-if-changed=codegen/generator.rs");
    println!("cargo:rerun-if-changed=codegen/lexer.rs");
    println!("cargo:rerun-if-changed=codegen/parser.rs");

    let bcp_file = parse_bcp_file(&spec_path)?;
    fs::create_dir_all(&out_dir)?;

    let mut module_contents = String::from("// @generated by build.rs\n");

    for msg in &bcp_file.messages {
        let binding = generate_message_binding(msg)?;
        let binding_path = out_dir.join(&binding.file);

        fs::write(&binding_path, binding.contents)?;
        module_contents.push_str(&format!(
            "include!(concat!(env!(\"OUT_DIR\"), \"/{}\"));\n",
            binding.file.display()
        ));
    }

    fs::write(out_dir.join("bcp_messages.rs"), module_contents)?;

    Ok(())
}

fn parse_bcp_file(path: &Path) -> io::Result<parser::BCPFile> {
    let contents = fs::read_to_string(path)?;
    let tokens = Lexer::new(&contents).decode().map_err(invalid_data)?;

    Parser::new(tokens).parse_tokens().map_err(invalid_data)
}

fn invalid_data(error: String) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, error)
}
